### ISSUE TITLE
Website appears down

### ISSUE THREAD

**Issue by zmughal** [lisah2u/ahiddendiscourse#1]
I see that the website is down at <http://www.downforeveryoneorjustme.com/ahiddendiscourse.com>.

By the way, I liked your [post about sensemaking](https://cdn.rawgit.com/lisah2u/ahiddendiscourse/master/public/blog/2013/02/17/the-cognitive-basis-for-academic-workflows/index.html). I was trying to reach it again.

**Comment by zmughal** [comment]
I see that the website is back up. Closing the issue!

**Comment by lisah2u** [comment]
Thanks! Had been asleep at wheel, so to speak.
